apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - image: nginx:1.15.6-alpine
        name: nginx
        ports:
        - name: http
          containerPort: 80
          hostPort: 80
        volumeMounts:
        - name: "config"
          mountPath: "/etc/nginx"
        - name: "certs"
          mountPath: "/etc/ssl"
      volumes:
      - name: config
        configMap:
          name: nginx-conf
      - name: certs
        secret:
          secretName: nginx-certs
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    worker_processes 1;
    error_log /dev/stdout info;

    events {
      worker_connections 10;
    }

    http {
      access_log /dev/stdout;

      server {
        listen 80;
        listen 443 ssl;

        ssl_certificate /etc/ssl/test.kataldi.com.crt;
        ssl_certificate_key /etc/ssl/test.kataldi.com.key;

        location /go {
          proxy_pass http://smallgo.default.svc.cluster.local:8080;
        }
      }
    }
